on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pull-request-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Pull artifacts
        run: python pull_artifacts.py ${{ github.event.pull_request.number }}
